{{ if .Values.waitForMetalNode }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.vms.namespace }} // FIXME vms is an array and will never contain any attribute .namespace
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{ end }}
