{{- $def := .Values.vmDefaults }}
{{- range $edvc, $edv := .Values.externalDataVolumes }}
{{- if coalesce $edv.registryCredentialsExternalSecret $def.registryCredentialsExternalSecret nil }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: es-registry-creds-{{ $edv.registryCredentialsSecret }}
  annotations:
  {{- $extraLabels := coalesce $edv.extraLabels $def.extraLabels nil }}
  {{- if $extraLabels }}
  labels:
    {{- range $lbl_k, $lbl_v := $extraLabels }}
    {{ $lbl_k | quote }}: {{ $lbl_v | quote }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: 90s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ $edv.registryCredentialsSecret }}
  dataFrom:
    - extract:
        key: {{ coalesce $edv.registryCredentialsExternalSecret $def.registryCredentialsExternalSecret }}
{{- end }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $edv.name }}-dv
  {{- if (coalesce $edv.namespace $def.externaldatavolumenamespace nil) }}
  namespace: {{ coalesce $edv.namespace $def.externaldatavolumenamespace }}
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- if $def.externalDataVolumeAnnodations }}
    {{ $def.externalDataVolumeAnnodations | toYaml }}
  {{- end }}
  {{- if $edv.annotations }}
    {{ $edv.annotations |toYaml }} // FIXME is this going to cause issues if the same label appears twice?
  {{- end }}
spec:
  source:
    {{- if eq (coalesce $edv.type $def.dataVolumeType) "registry"}}
    registry:
      url: {{ $edv.url }}
      {{- if $edv.registryCredentialsSecret }}
      secretRef: {{ $edv.registryCredentialsSecret }} 
      {{- end }}
    {{ else if eq (coalesce $edv.type $def.dataVolumeType) "http"}}
    http:
      url: {{ $edv.url }}
    {{- end }}
  {{- if $edv.size }}
  storage:
    resources:
      requests:
        storage: {{ $edv.size }}
  {{- end }}
{{- end }}
