{{- $def := .Values.vmDefaults }}
{{- range $edvc, $edv := .Values.externaldatavolumes }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $edv.name }}-dv
  {{- if (coalesce $edv.namespace $def.externaldatavolumenamespace nil) }}
  namespace: {{ coalesce $edv.namespace $def.externaldatavolumenamespace }}
  {{- end }}
  annotations:
  {{- if $def.externaldatavolumeannotations }}
    {{ $def.externaldatavolumeannotations | toYaml }}
  {{- end }}
  {{- if $edv.annotations }}
    {{ $edv.annotations |toYaml }} // FIXME is this going to cause issues if the same label appears twice?
  {{- end }}
spec:
  source:
    {{- if eq (coalesce $edv.type $def.datavolumetype) "registry"}}
    registry:
      url: {{ $edv.url }}
      {{- if $edv.credssecretref }}
      secretRef: {{ $edv.credssecretref }} 
      {{- end }}
    {{ else if eq (coalesce $edv.type $def.datavolumetype) "http"}}
    http:
      url: {{ $edv.url }}
    {{- end }}
  {{- if $edv.size }}
  storage:
    resources:
      requests:
        storage: {{ $edv.size }}
  {{- end }}
{{- end }}
