{{- $def := .Values.vmDefaults }}
{{- range $esk,$esv := .Values.registryCredentialExternalSecrets }}
{{- $name := coalesce $esv.name $esk }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: es-registry-creds-{{ $name }}
  namespace: {{ coalesce $esv.namespace $def.externalDataSourceNamespace }}
  annotations:
  {{- $extraLabels := coalesce $def.extraLabels nil }}
  {{- if $extraLabels }}
  labels:
    {{- range $lbl_k, $lbl_v := $extraLabels }}
    {{ $lbl_k | quote }}: {{ $lbl_v | quote }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: 90s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ $name }}
  dataFrom:
    - extract:
        key: {{ $esv.vaultKey }}
{{- end }}

